bind = SUPERCONTROL,mouse:273,submap,manage-window

# Manage-window submap
submap = manage-window
bind = ,escape,submap,reset
bindm = ,mouse:272,movewindow
bindm = SUPER,mouse:273,resizewindow
bind = SUPER,mouse:273,exec,~/.config/hypr/scripts/spawn-resizing-osd
# bind = ,mouse:272,submap,reset
# bind = ,mouse:273,submap,reset
bind = ,catchall,submap,reset
