bindd = SUPERALT,X,Enter power submap,submap,power

# Power submap
submap = power
bindd = ,s,Suspend system,exec, systemctl suspend
bindd = ,r,Reboot system,exec, systemctl reboot
bindd = ,p,Power off system,exec, systemctl poweroff
bindd = ,l,Lock screen,exec, $zsh "lock-screen"
bindd = ,e,Stop user session,exec, uwsm stop
bind = ,escape,submap,reset
bind = ,catchall,submap,reset
