# Right-ctrl hjkl arrow navigation submap
submap = ralt-nav
bind = ,escape,submap,reset

binde = , h, exec, wtype -k Left
binde = , j, exec, wtype -k Down
binde = , k, exec, wtype -k Up
binde = , l, exec, wtype -k Right
bindrt = ALT_R, ALT_R, submap, reset