# Right-ctrl hjkl arrow navigation submap
submap = ralt-nav
# bindr = ,Alt_R,submap,reset
bind = ,escape,submap,reset
bind = ,h,sendshortcut,,left,
bind = ,j,sendshortcut,,down,
bind = ,k,sendshortcut,,up,
bind = ,l,sendshortcut,,right,
bind = ,catchall,submap,reset