# Right-ctrl hjkl arrow navigation submap
submap = rctrl-nav
bindr = ,CTRL_R,submap,reset
bind = ,escape,submap,reset
bind = ,h,sendshortcut,,left,
bind = ,j,sendshortcut,,down,
bind = ,k,sendshortcut,,up,
bind = ,l,sendshortcut,,right,
bind = ,catchall,submap,reset