# Right-ctrl hjkl arrow navigation submap
submap = rctrl-nav
bindr = ,CTRL_R,submap,reset
bind = ,escape,submap,reset
bind = CTRL,h,sendshortcut,,left,
bind = CTRL,j,sendshortcut,,down,
bind = CTRL,k,sendshortcut,,up,
bind = CTRL,l,sendshortcut,,right,
bind = ,catchall,submap,reset