bindd = SUPERALT,R,Enter resize submap,submap,resize

# Resize submap
submap = resize
binde = ,h,resizeactive,-20 0
binde = ,l,resizeactive,20 0
binde = ,k,resizeactive,0 -20
binde = ,j,resizeactive,0 20
bind = ,escape,submap,reset
bind = ,catchall,submap,reset
