#!/usr/bin/env zsh
# shellcheck disable=SC1071

# [[ -f /usr/lib/xdg-desktop-portal ]] && /usr/lib/xdg-desktop-portal -r &!
# [[ -f /usr/lib/xdg-desktop-portal-hyprland ]] && /usr/lib/xdg-desktop-portal-hyprland  &! # https://wiki.hyprland.org/hyprland-wiki/pages/Useful-Utilities/Hyprland-desktop-portal/

[[ -f ~/.config/hypr/.secret/hidden.conf ]] || { mkdir -p ~/.config/hypr/.secret && touch ~/.config/hypr/.secret/hidden.conf; }

autoload start-idlemanager battery-saver # Load zsh functions to call later...
# start-idlemanager # Start idlemanager
battery-saver &! # Start battery-saver daemon
# fullscreen-event-handler &! # Call fullscreen-event-handler zsh functions

# hyprpm enable hyprwinwrap # Enable hyprland plugin
