#  ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗ 
#  ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
#  ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
#  ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
#  ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
#  ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ 
# https://wiki.hypr.land/Configuring/Variables/
# https://wiki.hypr.land/Configuring/Variables/#variable-types


source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/reserved-space.conf

exec-once = swww-daemon
exec-once = vicinae server
exec-once = nm-applet --indicator # Start network-manager applet
exec-once = udiskie --appindicator # Start automounter for removable media, like usb, thumb drives, mobile phones, digital cameras, etc.
exec-once = gnome-keyring-daemon -rd # Start gnome-keyring
exec-once = foot --server # Start foot server, this will reduced startup time and reduced memory footprint
exec-once = ags run &> ~/.cache/ags/logs 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # Enable polkit-gnome for run root-application with normal user like gparted.
exec-once = wl-paste --watch clipman store --no-persist # Start clipboard manager wayland
exec-once = zsh -i ~/.config/hypr/autostart # Run autostart file
exec-once = mpd # Music player daemon
exec-once = mpd-mpris

source = ~/.config/hypr/variables/general.conf
source = ~/.config/hypr/variables/decoration.conf
source = ~/.config/hypr/variables/animations-reduced.conf
source = ~/.config/hypr/variables/input.conf
source = ~/.config/hypr/variables/gestures.conf
source = ~/.config/hypr/variables/group.conf
source = ~/.config/hypr/variables/misc.conf
source = ~/.config/hypr/variables/layout.conf
source = ~/.config/hypr/variables/binds.conf
source = ~/.config/hypr/variables/xwayland.conf
source = ~/.config/hypr/variables/opengl.conf
source = ~/.config/hypr/variables/render.conf
source = ~/.config/hypr/variables/cursor.conf
source = ~/.config/hypr/variables/ecosystem.conf
source = ~/.config/hypr/variables/quirks.conf
source = ~/.config/hypr/variables/debug.conf

source = ~/.config/hypr/variables/master.conf
source = ~/.config/hypr/variables/dwindle.conf
# source = ~/.config/hypr/variables/scrolling.conf

source = ~/.config/hypr/variables/per-device.conf
source = ~/.config/hypr/variables/plugin.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrule.conf
