# vim:ft=hyprlang
submap = reset # Create global submapping, the keybinding below this line will be default, DO NOT REMOVE THIS LINE!!!
$zsh = /usr/bin/zsh -ic

# Keybind format: bind[flags] = MOD, key, dispatcher, params
# Reference: https://wiki.hypr.land/Configuring/Binds/

source = ~/.config/hypr/keybinds/core.conf
source = ~/.config/hypr/keybinds/navigation.conf
source = ~/.config/hypr/keybinds/workspaces.conf
source = ~/.config/hypr/keybinds/monitors.conf
source = ~/.config/hypr/keybinds/utilities.conf

# Submaps
source = ~/.config/hypr/keybinds/mouse-mode.conf
source = ~/.config/hypr/keybinds/manage-window.conf
source = ~/.config/hypr/keybinds/resize.conf
source = ~/.config/hypr/keybinds/power.conf
submap = reset
