# vim:ft=hyprlang

# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀
# https://wiki.hyprland.org/Configuring/Window-Rules/

# Workspace routing
windowrule = workspace 3,class:^(foot)$
windowrule = workspace 2,class:^(firefox|librewolf|qutebrowser|chromium|chrome)$

# Per-app behavior
windowrule = immediate,class:^(cs2)$
windowrule = pin,title:^(Picture-in-Picture)$
windowrule = float,title:^(Picture-in-Picture|.*Sharing Indicator.*)$
windowrule = float,class:^(pavucontrol|nemo|pcmanfm|thunar|file-roller|gucharmap)$
windowrule = animation slide left,class:^(nemo|pcmanfm|thunar|file-roller)$
windowrule = animation slide bottom,class:^(firefox|librewolf|qutebrowser)$
windowrule = move cursor -50% -50%,class:^(nemo|pcmanfm|thunar|file-roller|gucharmap)$
windowrule = nofocus,class:^(Ibus-ui-gtk3)$
windowrule = idleinhibit focus,class:^(mpv)$
windowrule = move 0 0,title:^(.*Sharing Indicator.*)$

# Layer effects
layerrule = blur, gtk-layer-shell
layerrule = blur, bottomlayer
layerrule = ignorealpha 0.18, bottomlayer
layerrule = ignorealpha 0.38, gtk-layer-shell
layerrule = blur, demo
layerrule = ignorealpha 0.38, demo
layerrule = blur, main-dashboard
layerrule = ignorealpha 0.38, main-dashboard
layerrule = blur, wofi
layerrule = ignorezero, wofi
layerrule = blur, vicinae
