# vim:ft=hyprlang

# ░█░█░▀█▀░█▀█░█▀▄░█▀█░█░█░░░█▀▄░█░█░█░░░█▀▀
# ░█▄█░░█░░█░█░█░█░█░█░█▄█░░░█▀▄░█░█░█░░░█▀▀
# ░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀
# https://wiki.hyprland.org/Configuring/Window-Rules/

# Workspace routing
windowrule = workspace 3, match:class ^(foot)$
windowrule = workspace 2, match:class ^(firefox|librewolf|qutebrowser|chromium|chrome)$

# Per-app behavior
windowrule = immediate on, match:class ^(cs2)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:title ^(Picture-in-Picture|.*Sharing Indicator.*)$
windowrule = float on, match:class ^(pavucontrol|nemo|pcmanfm|thunar|file-roller|gucharmap)$
windowrule = animation slide left, match:class ^(nemo|pcmanfm|thunar|file-roller)$
windowrule = animation slide bottom, match:class ^(firefox|librewolf|qutebrowser)$
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)), match:class ^(nemo|pcmanfm|thunar|file-roller|gucharmap)$
windowrule = no_focus on, match:class ^(Ibus-ui-gtk3)$
windowrule = idle_inhibit focus, match:class ^(mpv)$
windowrule = move 0 0, match:title ^(.*Sharing Indicator.*)$

# Layer effects
layerrule = blur on, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace bottomlayer
layerrule = ignore_alpha 0.18, match:namespace bottomlayer
layerrule = ignore_alpha 0.38, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace demo
layerrule = ignore_alpha 0.38, match:namespace demo
layerrule = blur on, match:namespace main-dashboard
layerrule = ignore_alpha 0.38, match:namespace main-dashboard
layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0.0, match:namespace wofi
layerrule = blur on, match:namespace vicinae
