# https://wiki.hypr.land/Configuring/Variables/#animations
# https://wiki.hypr.land/Configuring/Animations/

animations {
    enabled = true

    bezier = softOut, 0.22, 1, 0.36, 1
    bezier = softInOut, 0.4, 0, 0.2, 1
    bezier = overshot, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 5, softOut, slide
    animation = windowsIn, 1, 5, softOut, slide
    animation = windowsOut, 1, 4, softInOut, slide
    animation = windowsMove, 1, 4, softInOut

    animation = fade, 1, 4, softInOut
    animation = fadeIn, 1, 4, softOut
    animation = fadeOut, 1, 3, softInOut
    animation = fadeSwitch, 1, 3, softInOut
    animation = fadeShadow, 1, 3, softInOut
    animation = fadeDim, 1, 3, softInOut
    animation = fadeLayers, 1, 3, softInOut

    animation = layers, 1, 4, softOut, slide top
    animation = layersIn, 1, 4, softOut, slide top
    animation = layersOut, 1, 3, softInOut, fade

    animation = workspaces, 1, 6, softInOut, slidefade 15%
    animation = specialWorkspace, 1, 5, overshot, slidefadevert 20%

    animation = border, 1, 5, softInOut
    animation = borderangle, 0
    animation = zoomFactor, 1, 4, softInOut
}