# https://wiki.hypr.land/Configuring/Variables/#animations
# https://wiki.hypr.land/Configuring/Animations/

animations {
    enabled = true

    bezier = easeOut, 0.22, 1, 0.36, 1
    bezier = easeInOut, 0.4, 0, 0.2, 1
    bezier = softSpring, 0.2, 0.9, 0.2, 1.03

    animation = windows, 1, 4, easeOut, popin 93%
    animation = windowsIn, 1, 4, easeOut, popin 93%
    animation = windowsOut, 1, 3, easeInOut, popin 96%
    animation = windowsMove, 1, 4, easeInOut

    animation = fade, 1, 3, easeInOut
    animation = fadeIn, 1, 3, easeOut
    animation = fadeOut, 1, 2, easeInOut
    animation = fadeSwitch, 1, 2, easeInOut
    animation = fadeShadow, 1, 2, easeInOut
    animation = fadeDim, 1, 3, easeInOut
    animation = fadeLayers, 1, 3, easeInOut

    animation = layers, 1, 4, easeOut, popin 95%
    animation = layersIn, 1, 4, easeOut, popin 95%
    animation = layersOut, 1, 3, easeInOut, fade

    animation = workspaces, 1, 5, easeInOut, slidefade 12%
    animation = specialWorkspace, 1, 4, softSpring, slidefadevert 15%

    animation = border, 1, 4, easeInOut
    animation = borderangle, 0
    animation = zoomFactor, 1, 3, easeInOut
}