# https://wiki.hypr.land/Configuring/Variables/#debug
debug {
    overlay = false 	            # print the debug performance overlay. Disable VFR for accurate results.
    damage_blink = false 	        # (epilepsy warning!) flash areas updated with damage tracking
    gl_debugging = false 	        # enables OpenGL debugging with glGetError and EGL_KHR_debug, requires a restart after changing.
    disable_logs = true 	        # disable logging to a file
    disable_time = true 	        # disables time logging
    damage_tracking = 2 	        # redraw only the needed bits of the display. Do not change. (default: full - 2) monitor - 1, none - 0
    enable_stdout_logs = false 	    # enables logging to stdout
    manual_crash = 0 	            # set to 1 and then back to 0 to crash Hyprland.
    suppress_errors = false 	    # if true, do not display config file parsing errors.
    # watchdog_timeout = 5 	        # sets the timeout in seconds for watchdog to abort processing of a signal of the main thread. Set to 0 to disable.
    disable_scale_checks = false 	# disables verification of the scale factors. Will result in pixel alignment and rounding errors.
    error_limit = 5 	            # limits the number of displayed config file parsing errors.
    error_position = 0 	            # sets the position of the error bar. top - 0, bottom - 1
    colored_stdout_logs = true 	    # enables colors in the stdout logs.
    pass = false 	                # enables render pass debugging.
    full_cm_proto = false 	        # claims support for all cm proto features (requires restart)
}
