# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # pseudotile = false 	                    # enable pseudotiling. Pseudotiled windows retain their floating size when tiled.
    force_split = 0 	                    # 0 -> split follows mouse, 1 -> always split to the left (new = left or top) 2 -> always split to the right (new = right or bottom)
    preserve_split = false 	                # if enabled, the split (side/top) will not change regardless of what happens to the container.
    smart_split = false 	                # if enabled, allows a more precise control over the window split direction based on the cursor’s position.
    smart_resizing = true 	                # if enabled, resizing direction will be determined by the mouse’s position on the window (nearest to which corner).
    permanent_direction_override = false 	# if enabled, makes the preselect direction persist until either this mode is turned off or another direction is specified.
    special_scale_factor = 1 	            # specifies the scale factor of windows on the special workspace [0 - 1]
    split_width_multiplier = 1.0 	        # specifies the auto-split width multiplier. Useful on widescreen monitors.
    use_active_for_splits = true 	        # whether to prefer the active window or the mouse position for splits
    default_split_ratio = 1.0 	            # the default split ratio on window open. 1 means even 50/50 split. [0.1 - 1.9]
    split_bias = 0 	                        # specifies which window will receive the split ratio. 0 -> directional, 1 -> the current window
    precise_mouse_move = false 	            # bindm movewindow will drop the window more precisely depending on where your mouse is.
}
