# https://wiki.hypr.land/Configuring/Variables/#ecosystem
ecosystem {
    no_update_news = false 	        # disable the popup that shows up when you update hyprland to a new version.
    no_donation_nag = false 	    # disable the popup that shows up twice a year encouraging to donate.
    enforce_permissions = false 	# whether to enable permission control.
}
