# https://wiki.hypr.land/Configuring/Variables/#opengl
opengl {
    nvidia_anti_flicker = true 	# reduces flickering on nvidia at the cost of possible frame drops on lower-end GPUs. On non-nvidia, this is ignored.
}
