# https://wiki.hypr.land/Plugins/Using-Plugins/#installing--using-plugins
plugin {
    hyprwinwrap {
        class = GParted
        class = camera-mpv
        class = mpv
        class = eDEX-UI
    }
    hyprfocus {
        enabled = yes
        animate_floating = yes
        animate_workspacechange = yes
        focus_animation = shrink
        # Flash settings
        flash {
            flash_opacity = 0.95
            in_speed = 0.5
            out_speed = 3
        }
        # Shrink settings
        shrink {
            shrink_percentage = 0.95
            in_speed = 1
            out_speed = 2
        }
    }
}