# https://wiki.hypr.land/Configuring/Scrolling-Layout/
scrolling {
# hyprlang if !HYPRLAND_V_0_54
    fullscreen_on_one_column = true 	                # when enabled, a single column on a workspace will always span the entire screen.
    column_width = 0.5 	                                # the default width of a column, [0.1 - 1.0].
    focus_fit_method = 1 	                            # When a column is focused, what method should be used to bring it into view. 0 = center, 1 = fit
    follow_focus = true 	                            # when a window is focused, should the layout move to bring it into view automatically
    follow_min_visible = 0.4 	                        # when a window is focused, require that at least a given fraction of it is visible for focus to follow.
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0 	# A comma-separated list of preconfigured widths for colresize +conf/-conf
    wrap_focus = true 	                                # When enabled, causes layoutmsg focus l/r to wrap around at the beginning and end.
    wrap_swapcol = true 	                            # When enabled, causes layoutmsg swapcol l/r to wrap around at the beginning and end.
    direction = right 	                                # Direction in which new windows appear and the layout scrolls. left/right/down/up
# hyprlang endif
}
