# https://wiki.hypr.land/Configuring/Variables/#xwayland
xwayland {
    enabled = true 	                # allow running applications using X11
    use_nearest_neighbor = false 	# uses the nearest neighbor filtering for xwayland apps, making them pixelated rather than blurry
    force_zero_scaling = false 	    # forces a scale of 1 on xwayland windows on scaled displays.
    create_abstract_socket = false 	# Create the abstract Unix domain socket for XWayland connections. (XWayland restart is required for changes to take effect; Linux only)
}
