# Monitors
bindd = SUPER,Comma,Focus left monitor,focusmonitor,l
bindd = SUPER,Period,Focus right monitor,focusmonitor,r
bindd = SUPERALT,Comma,Move window to left monitor,movewindow,mon:l
bindd = SUPERALT,Period,Move window to right monitor,movewindow,mon:r
bindd = SUPERALT,left,Move current workspace to left monitor,movecurrentworkspacetomonitor,l
bindd = SUPERALT,right,Move current workspace to right monitor,movecurrentworkspacetomonitor,r
bindd = SUPERALT,S,Swap active workspaces between monitors,swapactiveworkspaces,current +1
