# Mouse-mode submap
submap = mouse-mode
bind = ,escape,submap,reset
binde = ,h,exec,movecursor -l
binde = ,j,exec,movecursor -d
binde = ,k,exec,movecursor -u
binde = ,l,exec,movecursor -r
bind = ,catchall,submap,reset
