# Mouse-mode submap
submap = mouse-mode
bind = ,escape,submap,reset
binde = ,h,exec,~/.config/hypr/scripts/handle-mousecursor -l
binde = ,j,exec,~/.config/hypr/scripts/handle-mousecursor -d
binde = ,k,exec,~/.config/hypr/scripts/handle-mousecursor -u
binde = ,l,exec,~/.config/hypr/scripts/handle-mousecursor -r
bind = ,catchall,submap,reset
