# Mouse-mode submap
submap = mouse-mode
bind = ,escape,submap,reset
bind = ,h,exec,~/.config/hypr/scripts/handle-mousecursor -l
bind = ,j,exec,~/.config/hypr/scripts/handle-mousecursor -d
bind = ,k,exec,~/.config/hypr/scripts/handle-mousecursor -u
bind = ,l,exec,~/.config/hypr/scripts/handle-mousecursor -r
bind = ,catchall,submap,reset
