# Focus, floating, and navigation
bindd = SUPER,space,Toggle floating,togglefloating,
bindd = SUPER,space,Center floating window,centerwindow,
bindd = SUPER,Tab,Cycle to next window,cyclenext,
bindd = SUPER,Tab,Raise active floating window,alterzorder,top
bindd = SUPERSHIFT,Tab,Cycle to previous window,cyclenext,prev
bindd = SUPERSHIFT,Tab,Raise active floating window,alterzorder,top
bindd = SUPER,left,Focus window left,movefocus,l
bindd = SUPER,right,Focus window right,movefocus,r
bindd = SUPER,up,Focus window up,movefocus,u
bindd = SUPER,down,Focus window down,movefocus,d
bindd = SUPERSHIFT,left,Swap with left window,swapwindow,l
bindd = SUPERSHIFT,right,Swap with right window,swapwindow,r
bindd = SUPERSHIFT,up,Swap with upper window,swapwindow,u
bindd = SUPERSHIFT,down,Swap with lower window,swapwindow,d
bindd = SUPER,grave,Focus current or last window,focuscurrentorlast,
bindd = SUPER,U,Focus urgent or last window,focusurgentorlast,
