# Launchers, media, and utilities
bindd = SUPERSHIFT,R,Force renderer reload,forcerendererreload,
bindd = SUPERSHIFT,L,Lock screen,exec, $zsh "lock-screen"
bindd = SUPER,E,Open file manager,exec, /usr/bin/nautilus
bindd = SUPER,P,Open app launcher,exec, vicinae
bindd = SUPERSHIFT,P,Open launcher modules,exec, pkill wofi || $zsh "wofi-core"
bindd = SUPER,V,Open clipboard history,exec, pkill wofi || $zsh "autoload wofi-clipboard; wofi-clipboard"
bindd = SUPER,semicolon,Open unicode picker,exec, pkill wofi || $zsh "autoload wofi-unicode; wofi-unicode"
bindd = SUPER,R,Reload Hyprland config,exec, hyprctl reload
bindd = SUPERCONTROL,return,Open terminal,exec, foot
bindd = SUPERCONTROL,B,Focus or launch browser,exec, ~/.config/hypr/scripts/focus-or-launch browser
bindd = SUPERCONTROL,E,Focus or launch editor,exec, ~/.config/hypr/scripts/focus-or-launch editor
bindd = SUPERCONTROL,T,Focus or launch terminal,exec, ~/.config/hypr/scripts/focus-or-launch terminal
binddel = ,XF86MonBrightnessUp,Increase brightness,exec, $zsh "brightness-handler up"
binddel = ,XF86MonBrightnessDown,Decrease brightness,exec, $zsh "brightness-handler down"
binddel = ,XF86AudioLowerVolume,Lower volume,exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binddel = ,XF86AudioRaiseVolume,Raise volume,exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binddl = ,XF86AudioMute,Toggle mute,exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindd = ,XF86AudioMicMute,Toggle microphone mute,exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindd = SUPERCONTROL,XF86AudioLowerVolume,Lower microphone gain,exec, wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-
bindd = SUPERCONTROL,XF86AudioRaiseVolume,Raise microphone gain,exec, wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+
binddl = ,XF86AudioPlay,Toggle play pause,exec, playerctl play-pause
binddl = ,XF86AudioPrev,Previous track,exec, playerctl previous
binddl = ,XF86AudioNext,Next track,exec, playerctl next
bindd = ,print,Take screenshot,exec, $zsh "screenshot"
bindd = SUPERSHIFT,S,Take area screenshot,exec, $zsh "autoload screenshot-area; screenshot-area"
bindd = SUPERSHIFT,T,Run screen OCR,exec, $zsh "screen-ocr"
bindd = SUPER,F10,Pass hotkey to OBS,pass, class:^(com\.obsproject\.Studio)$
bindd = SUPER,Insert,Open bookmark picker,exec, $zsh "bookmarks-grabber"

bindm = SUPER,mouse:273,resizewindow
bind = SUPER,mouse:273,exec, ~/.config/hypr/scripts/spawn-resizing-osd

bind = SUPERCONTROL,mouse:273,exec,ags run ~/.config/ags/window/context-menu/context-menu.tsx --gtk 4
bind = SUPER,mouse_down,exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.1')
bind = SUPER,mouse_up,exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.9) | if . < 1 then 1 else . end')
bind = SUPERSHIFT,mouse:274,exec, hyprctl -q keyword cursor:zoom_factor 1
