# Workspaces
bindd = SUPERSHIFT,mouse_up,Previous workspace,workspace,e-1
bindd = SUPERSHIFT,mouse_down,Next workspace,workspace,e+1
bind = SUPER,1,workspace,1
bind = SUPER,2,workspace,2
bind = SUPER,3,workspace,3
bind = SUPER,4,workspace,4
bind = SUPER,5,workspace,5
bind = SUPER,6,workspace,6
bind = SUPER,7,workspace,7
bind = SUPER,8,workspace,8
bind = SUPER,9,workspace,9
bind = SUPERCONTROL,1,focusworkspaceoncurrentmonitor,1
bind = SUPERCONTROL,2,focusworkspaceoncurrentmonitor,2
bind = SUPERCONTROL,3,focusworkspaceoncurrentmonitor,3
bind = SUPERCONTROL,4,focusworkspaceoncurrentmonitor,4
bind = SUPERCONTROL,5,focusworkspaceoncurrentmonitor,5
bind = SUPERCONTROL,6,focusworkspaceoncurrentmonitor,6
bind = SUPERCONTROL,7,focusworkspaceoncurrentmonitor,7
bind = SUPERCONTROL,8,focusworkspaceoncurrentmonitor,8
bind = SUPERCONTROL,9,focusworkspaceoncurrentmonitor,9
bindd = SUPER,0,Toggle special workspace,togglespecialworkspace,
bind = SUPERSHIFT,1,movetoworkspacesilent,1
bind = SUPERSHIFT,2,movetoworkspacesilent,2
bind = SUPERSHIFT,3,movetoworkspacesilent,3
bind = SUPERSHIFT,4,movetoworkspacesilent,4
bind = SUPERSHIFT,5,movetoworkspacesilent,5
bind = SUPERSHIFT,6,movetoworkspacesilent,6
bind = SUPERSHIFT,7,movetoworkspacesilent,7
bind = SUPERSHIFT,8,movetoworkspacesilent,8
bind = SUPERSHIFT,9,movetoworkspacesilent,9
bind = SUPERSHIFT,0,movetoworkspace,special
